# 
___
___
## ╭────────────────── Traceback (most recent call last) ───────────────────╮│ c:\pythonLearn\widgets.py:89 in on_button_pressed                      ││                                                                        ││    86 │   │   │   else:                                                ││    87 │   │   │   │   task=asyncio.create_task(delete_note(self.delete ││    88 │   │   │   app.Screen_my.remove_pane(app.Screen_my.active)      ││ ❱  89 │   │   │   await task                                           ││    90 │   │   if event.button.id.startswith("ankimake_"):              ││    91 │   │   │   anki_make(card.name)                                 ││    92 │   │   │   card.remove()                                        ││                                                                        ││ ╭──────────── locals ─────────────╮                                    ││ │ event = Pressed()               │                                    ││ │  self = Screen_anki(id='anki1') │                                    ││ ╰─────────────────────────────────╯                                    │╰────────────────────────────────────────────────────────────────────────╯UnboundLocalError: cannot access local variable 'task' where it is not 
associated with a value
___
## 
### 错误分析
- 

#### [Traceback](https://zh.wikipedia.org/wiki/Traceback)
你遇到了一个[UnboundLocalError](https://zh.wikipedia.org/wiki/UnboundLocalError)，这意味着你试图在[变量](https://zh.wikipedia.org/wiki/变量)被赋值之前访问它。

#### [代码](https://zh.wikipedia.org/wiki/代码)分析
在你的[代码](https://zh.wikipedia.org/wiki/代码)中，第89行试图`await task`，但在某些情况下，[变量](https://zh.wikipedia.org/wiki/变量)`task`可能没有被赋值。

#### 解决方案
你需要确保在所有情况下，[变量](https://zh.wikipedia.org/wiki/变量)`task`都被赋值。可以通过在赋值前初始化[变量](https://zh.wikipedia.org/wiki/变量)来解决这个问题。

```python
task = None
if some_condition:
    task = asyncio.create_task(delete_note)
    await task
```


### 
___
## if event.button.id == "sync":
            if self.delete_list==[]:
                pass
            else:
                task=asyncio.create_task(delete_note(self.delete_list))
            task=asyncio.create_task(anki_sync())
            for element in self.query(".no"):
                element.remove()
                self.lists.pop(element.name)

            self.delete_list=[]

            self.sync=True
            if self.lists=={}:
                app.Screen_my.remove_pane(app.Screen_my.active)
            await task
___
## 
### 代码问题分析
- 

#### [代码](https://zh.wikipedia.org/wiki/代码)分析
在你的[代码](https://zh.wikipedia.org/wiki/代码)中，[变量](https://zh.wikipedia.org/wiki/变量)`task`可能会被多次赋值，导致在某些情况下`await task`会等待错误的[任务](https://zh.wikipedia.org/wiki/任务)。

#### 解决方案
你需要确保每个[任务](https://zh.wikipedia.org/wiki/任务)都被正确地等待。可以通过使用多个[变量](https://zh.wikipedia.org/wiki/变量)来分别处理不同的[任务](https://zh.wikipedia.org/wiki/任务)。

```python
if event.button.id == "sync":
    if self.delete_list == []:
        delete_task = None
    else:
        delete_task = asyncio.create_task(delete_note(self.delete_list))
    
    sync_task = asyncio.create_task(anki_sync())
    
    for element in self.query(".no"):
        element.remove()
        self.lists.pop(element.name)

    self.delete_list = []
    self.sync = True
    
    if self.lists == {}:
        app.Screen_my.remove_pane(app.Screen_my.active)
    
    if delete_task:
        await delete_task
    await sync_task
```


### 
___
