# 
___
___
## ╭────────────────── Traceback (most recent call last) ───────────────────╮│ c:\pythonLearn\widgets.py:123 in on_button_pressed                     ││                                                                        ││    120 │   │   │   │   │   lists=self.good                             ││    121 │   │   │   │   │   app.Screen_my.remove_pane(app.Screen_my.act ││    122 │   │   │   │   else:                                           ││ ❱  123 │   │   │   │   │   lists=self.lists+self.good                  ││    124 │   │   │   │   for i in lists.items():                         ││    125 │   │   │   │   │   note+=i[1][0]+"?"+i[1][1]+"  "              ││    126 │   │   │   │   │   number.append(i[0])                         ││                                                                        ││ ╭────────────────────────────── locals ──────────────────────────────╮ ││ │ element = Grid(                                                    │ ││ │           │   id='ankigrid_4_2',                                   │ ││ │           │   name=[                                               │ ││ │           │   │   1723276864616,                                   │ ││ │           │   │   '場合の数的应用',                                │ ││ │           │   │                                                    │ ││ │           '場合の数在概率论和统计学中用于描述所有可能的情况数，常… │ ││ │           │   ]                                                    │ ││ │           )                                                        │ ││ │   event = Pressed()                                                │ ││ │    note = ''                                                       │ ││ │  number = []                                                       │ ││ │    self = Screen_anki(id='anki4')                                  │ ││ ╰────────────────────────────────────────────────────────────────────╯ │╰────────────────────────────────────────────────────────────────────────╯TypeError: unsupported operand type(s) for +: 'dict' and 'dict'
___
## 
### 错误分析
- 

#### [Traceback](https://zh.wikipedia.org/wiki/Traceback)
你遇到了一个[TypeError](https://zh.wikipedia.org/wiki/TypeError)，提示你不能对两个[字典](https://zh.wikipedia.org/wiki/字典)使用加号操作。具体来说，错误发生在[widgets.py](https://zh.wikipedia.org/wiki/widgets.py)文件的第123行。

#### [错误原因](https://zh.wikipedia.org/wiki/错误原因)
在第123行，你试图将两个[字典](https://zh.wikipedia.org/wiki/字典)相加：
```python
lists=self.lists+self.good
```
但是，[字典](https://zh.wikipedia.org/wiki/字典)类型不支持使用加号进行合并。

#### [解决方法](https://zh.wikipedia.org/wiki/解决方法)
你可以使用[update](https://zh.wikipedia.org/wiki/update)方法来合并两个[字典](https://zh.wikipedia.org/wiki/字典)：
```python
self.lists.update(self.good)
```
或者，如果你需要创建一个新的[字典](https://zh.wikipedia.org/wiki/字典)，可以使用[字典](https://zh.wikipedia.org/wiki/字典)解包：
```python
lists = {**self.lists, **self.good}
```

#### [示例](https://zh.wikipedia.org/wiki/示例)
假设你有两个[字典](https://zh.wikipedia.org/wiki/字典)：
```python
dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}
```
你可以这样合并它们：
```python
merged_dict = {**dict1, **dict2}
print(merged_dict)  # 输出: {'a': 1, 'b': 2, 'c': 3, 'd': 4}
```

希望这些信息能帮你解决问题！␃
___
